name: cncra2yr
version: '1.0'
summary: C&C Red Alert is a real-time strategy game.
description: |
 C&C: Red Alert 2 is a real-time strategy video game by Westwood Pacific, which was released for Microsoft Windows on October 23, 2000 as the follow-up to Command & Conquer: Red Alert. Red Alert 2 picks up at the conclusion of the Allied campaign of the first game. Its expansion is Command & Conquer: Yuri's Revenge.

 C&C: Red Alert 2 includes two different multi-player modes. One, LAN allows the player to play alongside friends and others without the use of an internet connection. The other, Online Play allows the player to play across the internet and against players from across the globe. LAN play allows for only Skirmish Mode that is available in single-player. Online play allows for tournaments, private games, public games, ladder ranking games and also contains a chat system. In 2005, control of online play for Red Alert 2 and a number of older C&C games was passed over from EA to XWIS, a community-run server.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: [amd64, i386]
base: core18

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

apps:
  cncra2yr:
    command: |
      bin/sommelier "$(find $WINEPREFIX/ -type f -name 'clientxna.exe' 2>/dev/null | head -1)"
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=" # Prevent pop-ups about Wine Gecko
      INSTALL_URL_CNC: "https://downloads.cncnet.org/CnCNet5_YR_Installer.exe"
      MONO_URL: "https://dl.winehq.org/wine/wine-mono/4.7.1/wine-mono-4.7.1.msi"
      TRICKS: "xna40 dotnet45"
      VIRTDESKTOP: 0
      LC_ALL: "C.UTF-8"
    plugs:
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - joystick
      - network
      - network-bind
      - opengl
      - process-control
      - pulseaudio
      - wayland
      - x11
      - gtk-3-themes
      - icon-themes
      - wine-runtime
      - wine-5-stable
  wineboot:
    command: bin/sommelier $SNAP/wine-platform/wine-stable/bin/wineboot
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=" # Prevent pop-ups about Wine Gecko
    plugs:
      - desktop
      - desktop-legacy
      - pulseaudio
      - wayland
      - x11
  winecfg:
    command: bin/sommelier $SNAP/wine-platform/wine-stable/bin/winecfg
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=" # Prevent pop-ups about Wine Gecko
    plugs:
      - desktop
      - desktop-legacy
      - pulseaudio
      - wayland
      - x11
  winetricks:
    command: bin/sommelier $SNAP/wine-runtime/bin/winetricks prefix="$WINEPREFIX"
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mshtml=" # Prevent pop-ups about Wine Gecko
      LC_ALL: "C.UTF-8"
    plugs:
      - desktop
      - desktop-legacy
      - network
      - pulseaudio
      - wayland
      - x11

parts:
  cncra2yr:
    plugin: dump
    source: ./snap/local/scripts
    override-build: |
      snapcraftctl build
      set -ex
      mkdir -p $SNAPCRAFT_PART_INSTALL/wine-runtime
      mkdir -p $SNAPCRAFT_PART_INSTALL/wine-platform
    organize:
      'sommelier': bin/
