name: cncra2yr
title: C&C Red Alert 2 Yuri's Revenge (WINE)
version: '1.0'
summary: C&C Red Alert is a real-time strategy game.
description: |
 C&C: Red Alert 2 is a real-time strategy video game by Westwood Pacific, which was released for Microsoft Windows on October 23, 2000 as the follow-up to Command & Conquer: Red Alert. Red Alert 2 picks up at the conclusion of the Allied campaign of the first game. Its expansion is Command & Conquer: Yuri's Revenge.

 C&C: Red Alert 2 includes two different multi-player modes. One, LAN allows the player to play alongside friends and others without the use of an internet connection. The other, Online Play allows the player to play across the internet and against players from across the globe. LAN play allows for only Skirmish Mode that is available in single-player. Online play allows for tournaments, private games, public games, ladder ranking games and also contains a chat system. In 2005, control of online play for Red Alert 2 and a number of older C&C games was passed over from EA to XWIS, a community-run server.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
base: core22
compression: lzo

plugs:
  gaming-mesa:
    interface: content
    target: $SNAP/graphics
    default-provider: gaming-graphics-core22
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes
  desktop:
    mount-host-font-cache: false
  shmem:
    interface: shared-memory
    private: true
  wine-runtime-c22:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core22
  wine-7-stable-c22:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-stable-core22

environment:
  LD_LIBRARY_PATH: $SNAP/graphics/lib/i386-linux-gnu:$SNAP/graphics/usr/lib:$SNAP/wine-runtime/usr/lib/i386-linux-gnu:$SNAP/wine-runtime/lib/i386-linux-gnu:$SNAP/wine-runtime/usr/lib/x86_64-linux-gnu:$SNAP/wine-runtime/lib/x86_64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  LIBGL_DRIVERS_PATH: $SNAP/graphics/usr/lib/i386-linux-gnu/dri:$SNAP/graphics/usr/lib/x86_64-linux-gnu/dri:${LIBGL_DRIVERS_PATH:+:$LIBGL_DRIVERS_PATH}
  WINEDLLOVERRIDES: "mshtml="    # Prevent pop-ups about Wine Gecko
  WINEPREFIX: "$SNAP_USER_COMMON/.wine"
  WINEARCH: "win64"
  INSTALL_URL_CNC: "https://downloads.cncnet.org/CnCNet5_YR_Installer.exe"
  TRICKS: "xna40 dotnet45"
  NO_AT_BRIDGE: 1
  DISABLE_WAYLAND: 1
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc
  TMPDIR: $XDG_RUNTIME_DIR

layout:
  /usr/share/libdrm:
    bind: $SNAP/wine-runtime/usr/share/libdrm

apps:
  cncra2yr:
    command-chain: [bin/desktop-launch]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Westwood/RA2/Resources/clientxna.exe"
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - opengl
      - audio-playback
      - hardware-observe
      - process-control
      - removable-media
      - shmem

  cncra2yrdx:
    command-chain: [bin/desktop-launch]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Westwood/RA2/Resources/clientdx.exe"
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - opengl
      - audio-playback
      - hardware-observe
      - process-control
      - removable-media
      - shmem

  cncra2yrogl:
    command-chain: [bin/desktop-launch]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Westwood/RA2/Resources/clientogl.exe"
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - opengl
      - audio-playback
      - hardware-observe
      - process-control
      - removable-media
      - shmem

  wine:
    command-chain: [bin/desktop-launch]
    command: bin/sommelier
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - opengl
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
      - shmem
  winetricks:
    command-chain: [bin/desktop-launch]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  cncra2yr:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      craftctl default
      set -ex
      mkdir -p sommelier/hooks ; mv pre-install sommelier/hooks ; mv pre-start sommelier/hooks ; cp -R -p sommelier $SNAPCRAFT_PART_INSTALL
      # Pre download required dependencies
      wget -q "https://dl.winehq.org/wine/wine-mono/7.0.0/wine-mono-7.0.0-x86.msi" -P winedata/wine
      wget -q "https://downloads.cncnet.org/CnCNet5_YR_Installer.exe" -P winedata
      wget -q "https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe" -P winedata/winetricks/dotnet40
      wget -q "https://download.microsoft.com/download/b/a/4/ba4a7e71-2906-4b2d-a0e1-80cf16844f5f/dotnetfx45_full_x86_x64.exe" -P winedata/winetricks/dotnet45
      wget -q "https://web.archive.org/web/20120325002813/https://download.microsoft.com/download/A/C/2/AC2C903B-E6E8-42C2-9FD7-BEBAC362A930/xnafx40_redist.msi" -P winedata/winetricks/xna40
      cp -R -p winedata $CRAFT_PART_INSTALL
    stage:
      - sommelier
      - winedata
    build-packages:
      - wget

  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "new-core22"